### ISSUE TITLE
Enable Dark Mode for whole app.

### ISSUE THREAD

**Issue by kirav5** [Repozo/hackerspree#4]
## Todo

1. Add dark mode toggle icon on top right corner.
2. By toggling the whole app should toggle to dark/light mode according to definitive Color palette(choose freely).

### Expected Output
![image](https://user-images.githubusercontent.com/42544589/104737696-9a313c80-576a-11eb-99a7-04b35a3db9f7.png)

**Comment by akshatjain-akj** [comment]
#6 this pull request will activate dark mode
